import ROOT

def Draw_HUPP_header():
   tex = ROOT.TLatex()
   tex.SetNDC()
   tex.SetTextAlign(31)
   tex.SetTextFont(42)
   tex.SetTextSize(0.05)
   tex.SetLineWidth(2)
   tex.DrawLatex(0.96,0.96,"x fb^{-1} (X TeV)")
   tex = ROOT.TLatex()
   tex.SetNDC()
   tex.SetTextFont(61)
   tex.SetTextSize(0.05)
   tex.SetLineWidth(2)
   tex.DrawLatex(0.18,0.96,"HUPP")
   tex = ROOT.TLatex()
   tex.SetNDC()
   tex.SetTextFont(52)
   tex.SetTextSize(0.05)
   tex.SetLineWidth(2)
   tex.DrawLatex(0.3,0.96,"Preliminary")
   return

def set_axis(histo,xaxis,yaxis):
   histo.GetXaxis().SetLabelFont(42)
   histo.GetXaxis().SetLabelOffset(0.007)
   histo.GetXaxis().SetLabelSize(0.05)
   histo.GetXaxis().SetTitleSize(0.06)
   histo.GetXaxis().SetTitleOffset(0.9)
   histo.GetXaxis().SetTitleFont(42)
   histo.GetXaxis().SetTitle(xaxis)
   histo.GetYaxis().SetLabelFont(42)
   histo.GetYaxis().SetLabelOffset(0.007)
   histo.GetYaxis().SetLabelSize(0.05)
   histo.GetYaxis().SetTitleSize(0.06)
   histo.GetYaxis().SetTitleOffset(1.35)
   histo.GetYaxis().SetTitleFont(42)
   histo.GetYaxis().SetTitle(yaxis)
   histo.GetZaxis().SetLabelFont(42)
   histo.GetZaxis().SetLabelOffset(0.007)
   histo.GetZaxis().SetLabelSize(0.05)
   histo.GetZaxis().SetTitleSize(0.06)
   histo.GetZaxis().SetTitleFont(42)
   histo.GetYaxis().SetDecimals()
   histo.GetYaxis().SetNdivisions(505)
   return

def DrawNicePlot(plot1,plot1name,path,fileName):

  can = ROOT.TCanvas("c",plot1name,800,800)
  plot1.SetTitle(plot1name)
  plot1.SetStats(0)
  plot1.SetLineColor(ROOT.kAzure+10)
  plot1.SetLineWidth(2)
  #plot1.SetAxisRange(0.1,(plot1.GetMaximum())*(plot1.GetMaximum()),"Y")
  plot1.Draw()
  plot1.GetYaxis().SetTitle("# of Events")
  plot1.GetYaxis().SetTitleSize(20)
  plot1.GetYaxis().SetTitleFont(43)
  plot1.GetYaxis().SetTitleOffset(1.55)
  plot1.GetYaxis().SetLabelFont(43)
  plot1.GetYaxis().SetLabelSize(15)
  leg = ROOT.TLegend(0.7,0.8,0.9,0.9)
  leg.AddEntry(plot1, plot1name,"l")
  leg.SetFillColor(0)
  leg.Draw()
  can.cd()
  can.SetGridx()
  #can.Update()
  can.SaveAs(path+fileName)

def DrawAdvancedPlot(plot1,plot1name,path,fileName):
  cb = ROOT.TCanvas("cb","cb",564,232,600,600)
  cb.SetHighLightColor(2)
  cb.Range(0,0,1,1)
  cb.SetFillColor(0)
  cb.SetBorderMode(0)
  cb.SetBorderSize(2)
  cb.SetTickx(1)
  cb.SetTicky(1)
  cb.SetLeftMargin(0.18)
  cb.SetRightMargin(0.04)
  cb.SetTopMargin(0.05)
  cb.SetBottomMargin(0.13)
  cb.SetFrameFillStyle(0)
  cb.SetFrameBorderMode(0)
  cb.SetFrameFillStyle(0)
  cb.SetFrameBorderMode(0)
  cb.cd()

  leg = ROOT.TLegend(0.65,0.5,0.93,0.925)
  leg.SetBorderSize(1)

  Pad1 = ROOT.TPad("Pad1", "Pad1", 0,0,1,1)
  Pad1.Draw()
  Pad1.cd()
  Pad1.SetFillColor(0)
  Pad1.SetBorderMode(0)
  Pad1.SetBorderSize(2)
  Pad1.SetLogy()
  Pad1.SetTickx(1)
  Pad1.SetTicky(1)
  Pad1.SetLeftMargin(0.18)
  Pad1.SetRightMargin(0.04)
  Pad1.SetTopMargin(0.055)
  Pad1.SetBottomMargin(0.12)
  Pad1.SetFrameFillStyle(0)
  Pad1.SetFrameBorderMode(0)
  Pad1.SetFrameFillStyle(0)
  Pad1.SetFrameBorderMode(0)
  Pad1.SetLogy()

  ROOT.gStyle.SetErrorX(.5)
  plot1.SetTitle("")
  plot1.SetStats(0)
  plot1.SetLineColor(ROOT.kAzure+10)
  plot1.SetLineWidth(2)
  plot1.SetAxisRange(0.11,(plot1.GetMaximum())*(plot1.GetMaximum()),"Y")
  set_axis(plot1,plot1name,"Events")
  plot1.Draw("E1")
  leg.AddEntry(plot1, plot1name,"l")
  Draw_HUPP_header()
  #Pad1.RedrawAxis()
  cb.SaveAs(path+fileName+".png")
  cb.SaveAs(path+fileName+".pdf")
  cb.SaveAs(path+fileName+".root")
